name: app
description: flutter project.
publish_to: 'none'

version: 1.2.0+20

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.2
  internet_connection_checker: ^0.0.1+3
  url_launcher: ^6.0.20
  #firebase
  firebase_core: ^1.14.1
  firebase_analytics: ^9.1.5
  firebase_messaging: ^11.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/